import Head from 'next/head'
import styled from 'styled-components'
import GlobalStyle from './components/GlobalStyle'
import { useState, useEffect } from 'react'
import accountData from './data/accounts.json'
import Link from 'next/link'

export default function Accounts() {
  const [accounts, setAccounts] = useState([])

  useEffect(() => {
    setAccounts(accountData.accounts)
  }, [])

  return (
    <div>
      <Head>
        <title>Cuentas</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <GlobalStyle />
      <Wrapper>
        <Title>Cuentas</Title>
        <Account title>
          <Text dark>ID</Text>
          <Text dark title>
            Número de Cuenta
          </Text>
          <Text dark title>
            Saldo
          </Text>
          <Text dark style={{ textIndent: '1.8rem' }}>
            Acción
          </Text>
        </Account>
        {accounts.map((account) => (
          <Account key={account.id}>
            <Text>{account.id}</Text>
            <Text>{account.accountNum}</Text>
            <Text>{account.saldo}</Text>
            <Link href={'/home'}>
              <Button type="button">Mostrar</Button>
            </Link>
            <Button primary type="button">
              Eliminar
            </Button>
          </Account>
        ))}
      </Wrapper>
    </div>
  )
}

const Wrapper = styled.div`
  width: 70%;
  top: 8%;
  left: 14%;
  padding: 2rem;
  display: grid;
  position: absolute;
  grid-row-gap: 0.5rem;
  background-color: white;
  border-radius: 15px;
`

const Account = styled.div`
  display: flex;
  align-items: center;
  height: 2.5rem;
  border: ${(props) => (props.title ? 'none' : '1px solid #e6d1d9')};
  background-color: white;
  border-radius: 5px;
`

const Text = styled.span`
  color: #630606;
  margin: ${(props) => (props.title ? '0 3.7rem' : '0 5rem')};
  font-weight: ${(props) => (props.dark ? 'bold' : 'normal')};
  display: inline;
`
const Button = styled.button`
  margin: 0 0.5rem;
  padding: 0.3rem 1rem;
  border-radius: 5px;
  border: solid 1px #a01d22;
  display: inline;
  background-color: ${(props) => (props.primary ? '#f7b4bb' : 'white')};
  font-weight: bold;
  color: #a01d22;
`
const Title = styled.span`
  display: grid;
  font-weight: bold;
  color: #690206;
  font-size: 2rem;
  margin: 1rem 4rem;
`
