import Head from 'next/head'
import styled from 'styled-components'
import axios from 'axios'
import { useState, useEffect } from 'react'

export default function Home() {
  const [animals, setAnimals] = useState([])

  useEffect(async () => {
    axios
      .get('api/animal')
      .then((res) => setAnimals(res.data))
      .catch((err) => console.error(err))
  }, [])

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {animals.map((animal, index) => (
        <Title key={index}>{animal.name}</Title>
      ))}
    </div>
  )
}

const Title = styled.h3`
  color: brown;
`
