import Head from 'next/head'
import styled from 'styled-components'
import LoginImg from '../public/assets/login-img.svg'
import GlobalStyle from './components/GlobalStyle'
import React, { useState } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()

  const [data, setData] = useState({
    user: '',
    password: ''
  })

  const handleInputChange = (event) => {
    setData({
      ...data,
      [event.target.name]: event.target.value
    })
  }

  const sendData = async (event) => {
    event.preventDefault()

    const pool = await fetch('http://localhost:3000/api/students', {
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json'
      },
      method: 'POST',
      body: JSON.stringify(data)
    })

    const cliente = await pool.json()

    if (cliente.userId > 0) {
      router.push(`http://localhost:3000/api/accounts/${cliente.userId}`)
    } else {
      window.alert('Usuario No Valido')
    }
  }

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <GlobalStyle />
      <Wrapper>
        <Login>
          <LoginForm onSubmit={sendData}>
            <Text title>Inicio de Sesión</Text>
            <FormInput
              placeholder="Nombre de usuario"
              name="user"
              onChange={handleInputChange}
            />
            <FormInput
              placeholder="Contraseña"
              name="password"
              onChange={handleInputChange}
            />

            <Button primary type="submit">
              Iniciar Sesión
            </Button>
            <Button>Registrarse</Button>
            <Text>
              <center>
                <u>¿Cambiar contraseña?</u>
              </center>
            </Text>
          </LoginForm>
        </Login>
        <PageDescription>
          <Text
            style={{ fontSize: '2rem', fontWeight: '700', color: '#690206' }}
          >
            TECBANK Web
          </Text>
        </PageDescription>
        <BankImage>
          <LoginImg
            style={{
              height: '100%',
              position: 'relative',
              left: '9%',
              top: '4%',
              margin: '0',
              padding: '0'
            }}
          />
        </BankImage>
      </Wrapper>
    </div>
  )
}

const Wrapper = styled.div`
  height: 75%;
  width: 64.11%;
  bottom: 12%;
  left: 19%;
  display: grid;
  position: absolute;
  grid-template-rows: 0.2fr 1fr;
  grid-template-columns: 0.6fr 1fr;
  border-radius: var(--border-radius);
  background-color: white;
`
const Login = styled.div`
  position: relative;
  bottom: 2rem;
  grid-column: 1;
  border-radius: var(--border-radius) 0 0 var(--border-radius);
`

const BankImage = styled.div`
  grid-row: 2;
  grid-column: 2;
  border-radius: 0 var(--border-radius) var(--border-radius) 0;
`
const FormInput = styled.input`
  outline: none;
  display: block;
  width: 100%;
  height: 1.8rem;
  margin: 0.5rem auto;
  border: 1px solid #df6967;
  background-color: #f4cdcc;
  color: #630606;
  text-indent: 0.5rem;
  border-radius: 5px;

  &::placeholder {
    color: #890f0d;
  }
`

const Button = styled.button`
  display: block;
  width: 100%;
  height: 1.8rem;
  margin: ${(props) => (props.primary ? '1.8rem ' : '0.4rem')} auto 0 auto;
  border: solid 1px ${(props) => (props.primary ? 'white ' : '#df6967')};
  border-radius: 5px;
  color: ${(props) => (props.primary ? 'white ' : '#df6967')};
  font-weight: bold;
  background-color: ${(props) => (props.primary ? '#df6967 ' : 'white')};
`

const LoginForm = styled.form`
  width: 18vw;
  margin: 6rem auto;
  padding-left: 2rem;
`
const Text = styled.span`
  display: block;
  font-weight: ${(props) => (props.title ? 'bold' : 'normal')};
  text-align: left;
  color: #890f0d;
  margin: 0.5rem auto;
`
const PageDescription = styled.div`
  position: relative;
  top: 4rem;
  padding-left: 4rem;
  grid-row: 1;
  grid-column: span 2;
`
